# Site settings
baseurl: '/cv'
url: &url https://torrocus.com

# Meta settings
description: "I'm a programmer and I'm proud of it."
title: Full Stack Developer using Ruby on Rails and JavaScript. Web app consultant and admin. | My resume

# Theme settings
chrome_mobile_color: '#1F272F' # color for chrome mobile searchbar
# blue turquoise green berry orange ceramic
theme_skin: personalized

# Tracker
analytics: UA-127739651-1

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Build settings
encoding: utf-8
compress_html: # - http://jch.penibelst.de/
  blanklines: false
  clippings: all
  comments: all
  # endings: all
  # profile: true
  # startings: all
  ignore:
    envs: development

# Development settings
port: 4000
host: 0.0.0.0
safe: false
